### ISSUE TITLE
"Build Status" at https://juliahub.com/ui/Packages/General/PRIMA is broken

### ISSUE THREAD

**Issue by zaikunzhang** [libprima/PRIMA.jl#13]
"Build Status" at https://juliahub.com/ui/Packages/General/PRIMA is broken. It was the case at the README, but I have fixed it https://github.com/libprima/PRIMA.jl/commit/a881cfdc27c5d18f792974703b892598494789a9

Is https://juliahub.com/ui/Packages/General/PRIMA automatically synced with the README?

**Comment by emmt** [comment]
To sync the Julia package, a new version must be registered.

To do that, simply bump version number (in [Project.toml](https://github.com/libprima/PRIMA.jl/blob/main/Project.toml)) and commit this change. Then, go to the commits page, click on the last commit and add the following comment:

```
@JuliaRegistrator register branch=main
```

You may read [this](https://pkgdocs.julialang.org/v1/compatibility/) for Julia rules regarding version number. In particular the special case of major version being 0.

I also, try to maintain a list of user visible changes in the file [NEWS.md](https://github.com/libprima/PRIMA.jl/blob/main/NEWS.md) so that it is easy for the users to figure out what's new and how to adapt to breaking changes if any.

In principle, Julia's [TagBot](https://github.com/JuliaRegistries/TagBot) automatically assign a tag with the version number to the repository once the new version is registered. However, for version 0.1.1, I had to do this manually (TagBot makes an issue with comments about how to do that). PRIM.jl is registered for TagBot, the configuration is in [.github/workflows/TagBot.yml](https://github.com/libprima/PRIMA.jl/blob/main/.github/workflows/TagBot.yml). 

I have a bunch of pending changes for `PRIMA.jl` to allow for running tests from the [CUTEst.jl](https://github.com/JuliaSmoothOptimizers/CUTEst.jl) suite. I can register a new version then.

**Comment by emmt** [comment]
As I wrote, you have to increase the version number first and commit this change:

> To do that, simply bump version number (in [Project.toml](https://github.com/libprima/PRIMA.jl/blob/main/Project.toml)) and commit this change. Then, go to the commits page, click on the last commit and add the following comment:

**Comment by emmt** [comment]
Apart from the new version issue (which will be solved the next time we register a new release, for instance after PR https://github.com/libprima/PRIMA.jl/pull/17 has been merged), the fix by @zaikunzhang fixes the issue, so I close it. We may keep a reference on this discussion as guiding rules for registering releases.
